#!/bin/bash

echo "Fixing Phantom Wallet Disconnection Issue"
echo "========================================="
echo ""
echo "The error '[PHANTOM] Failed to send message to service worker' means"
echo "Phantom's extension has lost connection to its background process."
echo ""

echo "SOLUTION 1: Restart Phantom Extension (Recommended)"
echo "---------------------------------------------------"
echo "1. Go to browser extensions (puzzle piece icon)"
echo "2. Find Phantom wallet"
echo "3. Click the three dots → 'Manage Extension'"
echo "4. Toggle OFF then ON the extension"
echo "5. Refresh the agentkit page"
echo "6. Phantom should auto-reconnect"
echo ""

echo "SOLUTION 2: Hard Reset Phantom"
echo "------------------------------"
echo "1. Close all browser tabs using Phantom"
echo "2. Go to: about:addons (Firefox) or chrome://extensions (Chrome)"
echo "3. Disable Phantom extension"
echo "4. Re-enable Phantom extension"
echo "5. Open Phantom and unlock with password"
echo "6. Switch to Ethereum network → Sepolia testnet"
echo "7. Reopen agentkit and try again"
echo ""

echo "SOLUTION 3: Use MetaMask Instead (Temporary)"
echo "--------------------------------------------"
echo "1. Disable Phantom extension"
echo "2. Install/Enable MetaMask"
echo "3. Switch MetaMask to Sepolia testnet"
echo "4. The app will auto-detect MetaMask"
echo ""

echo "SOLUTION 4: Full Browser Reset"
echo "------------------------------"
echo "1. Close browser completely"
echo "2. Clear browser cache/cookies for localhost"
echo "3. Restart browser"
echo "4. Unlock Phantom"
echo "5. Make sure on Ethereum → Sepolia"
echo ""

echo "Testing if backend is still responsive..."
curl -s http://localhost:8001/api/proof/test_123/ethereum -w "\nBackend response time: %{time_total}s\n" | jq '.proof' | head -5 2>/dev/null || echo "Backend error"

echo ""
echo "The issue is NOT with your code - Phantom's service worker"
echo "disconnection is a known browser extension issue that happens"
echo "after extended use or browser sleep/wake cycles."