#!/bin/bash

echo "🚀 Manual Solana Installation Guide"
echo ""
echo "Since the automated installation had issues, here are the manual steps:"
echo ""
echo "1. Install Rust (if not already installed):"
echo "   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
echo "   source $HOME/.cargo/env"
echo ""
echo "2. Install Solana CLI:"
echo "   sh -c \"\$(curl -sSfL https://release.solana.com/stable/install)\""
echo "   export PATH=\"\$HOME/.local/share/solana/install/active_release/bin:\$PATH\""
echo ""
echo "3. Install Anchor (may take 10-15 minutes):"
echo "   cargo install --git https://github.com/coral-xyz/anchor avm --locked"
echo "   avm install latest"
echo "   avm use latest"
echo ""
echo "4. Configure for Devnet:"
echo "   solana config set --url https://api.devnet.solana.com"
echo "   solana-keygen new --no-passphrase"
echo "   solana airdrop 2"
echo ""
echo "Alternatively, use Solana Playground (no install needed):"
echo "https://beta.solpg.io/"