#!/bin/bash

echo "To push to your hshadab/verifiable-agentkit repository:"
echo ""
echo "Option 1: Use HTTPS with your hshadab token"
echo "  git push https://hshadab:YOUR_GITHUB_TOKEN@github.com/hshadab/verifiable-agentkit.git main"
echo ""
echo "Option 2: Clear stored credentials and re-authenticate"
echo "  git config --global --unset credential.helper"
echo "  git push origin main"
echo "  (Enter hshadab username and token when prompted)"
echo ""
echo "Option 3: Push to ICME-Lab instead"
echo "  git push icme-lab main"
echo ""
echo "The changes ready to push include:"
echo "- Centralized configuration files (config.js, config.py)"
echo "- Cleanup tools (cleanup.sh)"
echo "- Test organization (tests/run_tests.sh)"
echo "- Documentation (IMPORTANT_FILES.md)"