#!/bin/bash

echo "=== Testing Verification Fix ==="
echo ""
echo "The fix implements:"
echo "1. Detection of proof IDs in verify commands"
echo "2. Loading proof data from disk when verifying by ID"
echo "3. Proper parsing in OpenAI workflow parser"
echo ""
echo "To test:"
echo "1. Open http://127.0.0.1:8001"
echo "2. Type: Generate KYC proof"
echo "3. Wait for proof generation"
echo "4. Click 'Verify Locally' - should now work!"
echo "5. For blockchain verification:"
echo "   - Click 'Verify on Solana' (recommended with Phantom)"
echo "   - Click 'Verify on Ethereum' (will show Phantom warning)"
echo ""
echo "The fix allows verifying proofs across different workflow instances."
echo ""
echo "Backend changes:"
echo "- workflowExecutor_generic.js: Added verifyProofFromDisk method"
echo "- openai_workflow_parser_enhanced.py: Added proof_id parsing"
echo ""
echo "✅ Ready to test!"